- name: Configure droplets for learning docker
  hosts: all
  tasks:
    - name: Update software
      apt:
        name: "*"
        state: latest
        update_cache: yes

    - name: Install required software
      apt:
        state: latest
        pkg:
          - docker.io
          - docker-compose
          - git

    - name: copy motd
      copy:
        src: ./motd
        dest: /etc/motd
        owner: root
        group: root
        mode: '0644'